# This is a basic workflow to help you get started with Actions

name: update_gem_data

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    - cron: '00 01,13 * * *' # regular job (1pm & 1am): '00 01,13 * * *' // every 15 minutes: */15 * * * *
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - name: checkout repo content
            uses: actions/checkout@v4 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v4
            with:
              python-version: 3.11 #install the python needed
              cache: 'pip' # caching pip dependencies 

          - name: Install Dependencies
          #   if: steps.cache.outputs.cache-hit != 'true'
            run: |
              echo "Installing dependencies and caching them."
              pip install -r requirements.txt
      
          #- name: Install dependencies
          #  run: | 
          #    pip install -r requirements.txt
              
          - name: execute python script skillgems # run the run.py to get the latest data
            run: |
              python update_gem_data.py
              
          - name: Commit and Push Changes
            run: |
              git config user.name "grummble-ai"
              git config user.email "73717764+grummble-ai@users.noreply.github.com"
              git add -u || echo "Adding didn't work"
              git commit -m "Commit skill gem data with GitHub Actions" || echo "Commit didn't work"
              git push -f origin main || echo "Pushing didn't work"
              
